package com.visosoft.tvshowinfo.service.impl.showupdater.tvrage;

//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
//Any modifications to this file will be lost upon recompilation of the source schema.
//Generated on: 2010.07.18 at 01:58:03 PM CEST
//

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
* <p>Java class for anonymous complex type.
*
* <p>The following schema fragment specifies the expected content contained within this class.
*
* <pre>
* &lt;complexType>
*   &lt;complexContent>
*     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*       &lt;sequence>
*         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
*         &lt;element name="totalseasons" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
*         &lt;element name="Episodelist">
*           &lt;complexType>
*             &lt;complexContent>
*               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*                 &lt;sequence>
*                   &lt;element name="Season" maxOccurs="unbounded">
*                     &lt;complexType>
*                       &lt;complexContent>
*                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*                           &lt;sequence>
*                             &lt;element name="episode" maxOccurs="unbounded">
*                               &lt;complexType>
*                                 &lt;complexContent>
*                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*                                     &lt;sequence>
*                                       &lt;element name="epnum" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
*                                       &lt;element name="seasonnum" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
*                                       &lt;element name="prodnum" type="{http://www.w3.org/2001/XMLSchema}string"/>
*                                       &lt;element name="airdate" type="{http://www.w3.org/2001/XMLSchema}date"/>
*                                       &lt;element name="link" type="{http://www.w3.org/2001/XMLSchema}string"/>
*                                       &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
*                                     &lt;/sequence>
*                                   &lt;/restriction>
*                                 &lt;/complexContent>
*                               &lt;/complexType>
*                             &lt;/element>
*                           &lt;/sequence>
*                           &lt;attribute name="no" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
*                         &lt;/restriction>
*                       &lt;/complexContent>
*                     &lt;/complexType>
*                   &lt;/element>
*                 &lt;/sequence>
*               &lt;/restriction>
*             &lt;/complexContent>
*           &lt;/complexType>
*         &lt;/element>
*       &lt;/sequence>
*     &lt;/restriction>
*   &lt;/complexContent>
* &lt;/complexType>
* </pre>
*
*
*/
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
 "name",
 "totalseasons",
 "episodelist"
})
@XmlRootElement(name = "Show")
public class ShowXmlTVRage {

 @XmlElement(required = true)
 protected String name;
 @XmlSchemaType(name = "unsignedByte")
 protected short totalseasons;
 @XmlElement(name = "Episodelist", required = true)
 protected ShowXmlTVRage.Episodelist episodelist;

 /**
  * Gets the value of the name property.
  *
  * @return
  *     possible object is
  *     {@link String }
  *
  */
 public String getName() {
     return name;
 }

 /**
  * Sets the value of the name property.
  *
  * @param value
  *     allowed object is
  *     {@link String }
  *
  */
 public void setName(String value) {
     this.name = value;
 }

 /**
  * Gets the value of the totalseasons property.
  *
  */
 public short getTotalseasons() {
     return totalseasons;
 }

 /**
  * Sets the value of the totalseasons property.
  *
  */
 public void setTotalseasons(short value) {
     this.totalseasons = value;
 }

 /**
  * Gets the value of the episodelist property.
  *
  * @return
  *     possible object is
  *     {@link ShowXmlTVRage.Episodelist }
  *
  */
 public ShowXmlTVRage.Episodelist getEpisodelist() {
     return episodelist;
 }

 /**
  * Sets the value of the episodelist property.
  *
  * @param value
  *     allowed object is
  *     {@link ShowXmlTVRage.Episodelist }
  *
  */
 public void setEpisodelist(ShowXmlTVRage.Episodelist value) {
     this.episodelist = value;
 }


 /**
  * <p>Java class for anonymous complex type.
  *
  * <p>The following schema fragment specifies the expected content contained within this class.
  *
  * <pre>
  * &lt;complexType>
  *   &lt;complexContent>
  *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
  *       &lt;sequence>
  *         &lt;element name="Season" maxOccurs="unbounded">
  *           &lt;complexType>
  *             &lt;complexContent>
  *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
  *                 &lt;sequence>
  *                   &lt;element name="episode" maxOccurs="unbounded">
  *                     &lt;complexType>
  *                       &lt;complexContent>
  *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
  *                           &lt;sequence>
  *                             &lt;element name="epnum" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
  *                             &lt;element name="seasonnum" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
  *                             &lt;element name="prodnum" type="{http://www.w3.org/2001/XMLSchema}string"/>
  *                             &lt;element name="airdate" type="{http://www.w3.org/2001/XMLSchema}date"/>
  *                             &lt;element name="link" type="{http://www.w3.org/2001/XMLSchema}string"/>
  *                             &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
  *                           &lt;/sequence>
  *                         &lt;/restriction>
  *                       &lt;/complexContent>
  *                     &lt;/complexType>
  *                   &lt;/element>
  *                 &lt;/sequence>
  *                 &lt;attribute name="no" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
  *               &lt;/restriction>
  *             &lt;/complexContent>
  *           &lt;/complexType>
  *         &lt;/element>
  *       &lt;/sequence>
  *     &lt;/restriction>
  *   &lt;/complexContent>
  * &lt;/complexType>
  * </pre>
  *
  *
  */
 @XmlAccessorType(XmlAccessType.FIELD)
 @XmlType(name = "", propOrder = {
     "season"
 })
 public static class Episodelist {

     @XmlElement(name = "Season", required = true)
     protected List<ShowXmlTVRage.Episodelist.Season> season;

     /**
      * Gets the value of the season property.
      *
      * <p>
      * This accessor method returns a reference to the live list,
      * not a snapshot. Therefore any modification you make to the
      * returned list will be present inside the JAXB object.
      * This is why there is not a <CODE>set</CODE> method for the season property.
      *
      * <p>
      * For example, to add a new item, do as follows:
      * <pre>
      *    getSeason().add(newItem);
      * </pre>
      *
      *
      * <p>
      * Objects of the following type(s) are allowed in the list
      * {@link ShowXmlTVRage.Episodelist.Season }
      *
      *
      */
     public List<ShowXmlTVRage.Episodelist.Season> getSeason() {
         if (season == null) {
             season = new ArrayList<ShowXmlTVRage.Episodelist.Season>();
         }
         return this.season;
     }


     /**
      * <p>Java class for anonymous complex type.
      *
      * <p>The following schema fragment specifies the expected content contained within this class.
      *
      * <pre>
      * &lt;complexType>
      *   &lt;complexContent>
      *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
      *       &lt;sequence>
      *         &lt;element name="episode" maxOccurs="unbounded">
      *           &lt;complexType>
      *             &lt;complexContent>
      *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
      *                 &lt;sequence>
      *                   &lt;element name="epnum" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
      *                   &lt;element name="seasonnum" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
      *                   &lt;element name="prodnum" type="{http://www.w3.org/2001/XMLSchema}string"/>
      *                   &lt;element name="airdate" type="{http://www.w3.org/2001/XMLSchema}date"/>
      *                   &lt;element name="link" type="{http://www.w3.org/2001/XMLSchema}string"/>
      *                   &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
      *                 &lt;/sequence>
      *               &lt;/restriction>
      *             &lt;/complexContent>
      *           &lt;/complexType>
      *         &lt;/element>
      *       &lt;/sequence>
      *       &lt;attribute name="no" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
      *     &lt;/restriction>
      *   &lt;/complexContent>
      * &lt;/complexType>
      * </pre>
      *
      *
      */
     @XmlAccessorType(XmlAccessType.FIELD)
     @XmlType(name = "", propOrder = {
         "episode"
     })
     public static class Season {

         @XmlElement(required = true)
         protected List<ShowXmlTVRage.Episodelist.Season.Episode> episode;
         @XmlAttribute(name = "no", required = true)
         @XmlSchemaType(name = "unsignedByte")
         protected short no;

         /**
          * Gets the value of the episode property.
          *
          * <p>
          * This accessor method returns a reference to the live list,
          * not a snapshot. Therefore any modification you make to the
          * returned list will be present inside the JAXB object.
          * This is why there is not a <CODE>set</CODE> method for the episode property.
          *
          * <p>
          * For example, to add a new item, do as follows:
          * <pre>
          *    getEpisode().add(newItem);
          * </pre>
          *
          *
          * <p>
          * Objects of the following type(s) are allowed in the list
          * {@link ShowXmlTVRage.Episodelist.Season.Episode }
          *
          *
          */
         public List<ShowXmlTVRage.Episodelist.Season.Episode> getEpisode() {
             if (episode == null) {
                 episode = new ArrayList<ShowXmlTVRage.Episodelist.Season.Episode>();
             }
             return this.episode;
         }

         /**
          * Gets the value of the no property.
          *
          */
         public short getNo() {
             return no;
         }

         /**
          * Sets the value of the no property.
          *
          */
         public void setNo(short value) {
             this.no = value;
         }


         /**
          * <p>Java class for anonymous complex type.
          *
          * <p>The following schema fragment specifies the expected content contained within this class.
          *
          * <pre>
          * &lt;complexType>
          *   &lt;complexContent>
          *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
          *       &lt;sequence>
          *         &lt;element name="epnum" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
          *         &lt;element name="seasonnum" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
          *         &lt;element name="prodnum" type="{http://www.w3.org/2001/XMLSchema}string"/>
          *         &lt;element name="airdate" type="{http://www.w3.org/2001/XMLSchema}date"/>
          *         &lt;element name="link" type="{http://www.w3.org/2001/XMLSchema}string"/>
          *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
          *       &lt;/sequence>
          *     &lt;/restriction>
          *   &lt;/complexContent>
          * &lt;/complexType>
          * </pre>
          *
          *
          */
         @XmlAccessorType(XmlAccessType.FIELD)
         @XmlType(name = "", propOrder = {
             "epnum",
             "seasonnum",
             "prodnum",
             "airdate",
             "link",
             "title"
         })
         public static class Episode {

             @XmlSchemaType(name = "unsignedByte")
             protected short epnum;
             @XmlSchemaType(name = "unsignedByte")
             protected short seasonnum;
             @XmlElement(required = true)
             protected String prodnum;
             @XmlElement(required = true)
             @XmlSchemaType(name = "date")
             protected XMLGregorianCalendar airdate;
             @XmlElement(required = true)
             protected String link;
             @XmlElement(required = true)
             protected String title;

             /**
              * Gets the value of the epnum property.
              *
              */
             public short getEpnum() {
                 return epnum;
             }

             /**
              * Sets the value of the epnum property.
              *
              */
             public void setEpnum(short value) {
                 this.epnum = value;
             }

             /**
              * Gets the value of the seasonnum property.
              *
              */
             public short getSeasonnum() {
                 return seasonnum;
             }

             /**
              * Sets the value of the seasonnum property.
              *
              */
             public void setSeasonnum(short value) {
                 this.seasonnum = value;
             }

             /**
              * Gets the value of the prodnum property.
              *
              * @return
              *     possible object is
              *     {@link String }
              *
              */
             public String getProdnum() {
                 return prodnum;
             }

             /**
              * Sets the value of the prodnum property.
              *
              * @param value
              *     allowed object is
              *     {@link String }
              *
              */
             public void setProdnum(String value) {
                 this.prodnum = value;
             }

             /**
              * Gets the value of the airdate property.
              *
              * @return
              *     possible object is
              *     {@link XMLGregorianCalendar }
              *
              */
             public XMLGregorianCalendar getAirdate() {
                 return airdate;
             }

             /**
              * Sets the value of the airdate property.
              *
              * @param value
              *     allowed object is
              *     {@link XMLGregorianCalendar }
              *
              */
             public void setAirdate(XMLGregorianCalendar value) {
                 this.airdate = value;
             }

             /**
              * Gets the value of the link property.
              *
              * @return
              *     possible object is
              *     {@link String }
              *
              */
             public String getLink() {
                 return link;
             }

             /**
              * Sets the value of the link property.
              *
              * @param value
              *     allowed object is
              *     {@link String }
              *
              */
             public void setLink(String value) {
                 this.link = value;
             }

             /**
              * Gets the value of the title property.
              *
              * @return
              *     possible object is
              *     {@link String }
              *
              */
             public String getTitle() {
                 return title;
             }

             /**
              * Sets the value of the title property.
              *
              * @param value
              *     allowed object is
              *     {@link String }
              *
              */
             public void setTitle(String value) {
                 this.title = value;
             }

         }

     }

 }

}
